name: crm_app
description: "Una app CRM"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+6

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  file_picker: ^8.0.3
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.0
  floating_action_bubble_custom: ^1.0.0+2
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_dotenv: ^5.1.0
  flutter_file_downloader: ^1.2.1
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.4.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_polyline_points: ^2.1.0
  flutter_riverpod: ^2.4.10
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  formz: ^0.6.1
  geolocator: ^11.0.0
  go_router: ^13.1.0
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.6+2
  google_polyline_points: ^0.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  open_file: ^3.3.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  phone_state: ^1.0.4
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  syncfusion_flutter_calendar: ^24.2.4
  table_calendar: ^3.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  launcher_name: ^1.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"

launcher_name:
  default: "Force MR"
  es: "Force MR"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/icon/
    - google_fonts/montserrat_alternates/
